source: test/source
dest: test/dest

server:
  port: 4567

plugins:
  - name: copydest
    options:
      ignored:
        - tailwind.config.js 
  - name: sass
    options:
      watch: "**/*.scss"
  - name: tailwind
  - name: imagecompressor
  - name: hotreload